# Generated by Django 3.0.2 on 2021-02-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200320_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='synopsis',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='price',
        ),
    ]
