# Generated by Django 3.0.2 on 2021-02-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210216_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='number',
            new_name='synopsis',
        ),
    ]
