# Generated by Django 3.0.2 on 2021-02-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210217_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='synopsis',
            new_name='price',
        ),
    ]
